# Generated by Django 6.0.4 on 2026-05-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
