# Generated by Django 6.0.4 on 2026-05-05 19:51

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images', validators=[product.validators.validate_file_size]),
        ),
    ]
